//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/takuumi/Projects/StudyANTLR/Part3/STtoKVScript/STGrammer.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class STGrammerParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		NEWLINE=1, PLUS=2, MINUS=3, ASTERISK=4, SLASH=5, POW=6, LT=7, GT=8, LE=9, 
		GE=10, EQ=11, NEQ=12, ASSIGN=13, OUTREF=14, RANGE=15, COMMA=16, OPEN_PAREN=17, 
		CLOSE_PAREN=18, SEMI_COLON=19, CASE=20, OF=21, END_CASE=22, REPEAT=23, 
		UNTIL=24, END_REPEAT=25, IDENTIFIER=26, WS=27, SINGLE_LINE_COMMENT=28;
	public const int
		RULE_input = 0, RULE_oneline = 1, RULE_stlang = 2, RULE_expr = 3, RULE_define = 4, 
		RULE_linecomment = 5;
	public static readonly string[] ruleNames = {
		"input", "oneline", "stlang", "expr", "define", "linecomment"
	};

	private static readonly string[] _LiteralNames = {
		null, null, "'+'", "'-'", "'*'", "'/'", "'**'", "'<'", "'>'", "'<='", 
		"'>='", "'='", "'<>'", "':='", "'=>'", "'..'", "','", "'('", "')'", "';'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "NEWLINE", "PLUS", "MINUS", "ASTERISK", "SLASH", "POW", "LT", "GT", 
		"LE", "GE", "EQ", "NEQ", "ASSIGN", "OUTREF", "RANGE", "COMMA", "OPEN_PAREN", 
		"CLOSE_PAREN", "SEMI_COLON", "CASE", "OF", "END_CASE", "REPEAT", "UNTIL", 
		"END_REPEAT", "IDENTIFIER", "WS", "SINGLE_LINE_COMMENT"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "STGrammer.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static STGrammerParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public STGrammerParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public STGrammerParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class InputContext : ParserRuleContext {
		public ITerminalNode Eof() { return GetToken(STGrammerParser.Eof, 0); }
		public ITerminalNode[] NEWLINE() { return GetTokens(STGrammerParser.NEWLINE); }
		public ITerminalNode NEWLINE(int i) {
			return GetToken(STGrammerParser.NEWLINE, i);
		}
		public OnelineContext[] oneline() {
			return GetRuleContexts<OnelineContext>();
		}
		public OnelineContext oneline(int i) {
			return GetRuleContext<OnelineContext>(i);
		}
		public InputContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_input; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISTGrammerVisitor<TResult> typedVisitor = visitor as ISTGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInput(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public InputContext input() {
		InputContext _localctx = new InputContext(Context, State);
		EnterRule(_localctx, 0, RULE_input);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 18;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,1,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 13;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					if (_la==IDENTIFIER || _la==SINGLE_LINE_COMMENT) {
						{
						State = 12; oneline();
						}
					}

					State = 15; Match(NEWLINE);
					}
					} 
				}
				State = 20;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,1,Context);
			}
			State = 22;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==IDENTIFIER || _la==SINGLE_LINE_COMMENT) {
				{
				State = 21; oneline();
				}
			}

			State = 24; Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OnelineContext : ParserRuleContext {
		public OnelineContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_oneline; } }
	 
		public OnelineContext() { }
		public virtual void CopyFrom(OnelineContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class Expr_stlangContext : OnelineContext {
		public StlangContext stlang() {
			return GetRuleContext<StlangContext>(0);
		}
		public Expr_stlangContext(OnelineContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISTGrammerVisitor<TResult> typedVisitor = visitor as ISTGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpr_stlang(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Expr_stlinecommentContext : OnelineContext {
		public LinecommentContext linecomment() {
			return GetRuleContext<LinecommentContext>(0);
		}
		public Expr_stlinecommentContext(OnelineContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISTGrammerVisitor<TResult> typedVisitor = visitor as ISTGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpr_stlinecomment(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OnelineContext oneline() {
		OnelineContext _localctx = new OnelineContext(Context, State);
		EnterRule(_localctx, 2, RULE_oneline);
		try {
			State = 28;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case IDENTIFIER:
				_localctx = new Expr_stlangContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 26; stlang();
				}
				break;
			case SINGLE_LINE_COMMENT:
				_localctx = new Expr_stlinecommentContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 27; linecomment();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StlangContext : ParserRuleContext {
		public StlangContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stlang; } }
	 
		public StlangContext() { }
		public virtual void CopyFrom(StlangContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class Expr_exprContext : StlangContext {
		public ITerminalNode IDENTIFIER() { return GetToken(STGrammerParser.IDENTIFIER, 0); }
		public ITerminalNode ASSIGN() { return GetToken(STGrammerParser.ASSIGN, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ITerminalNode SEMI_COLON() { return GetToken(STGrammerParser.SEMI_COLON, 0); }
		public Expr_exprContext(StlangContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISTGrammerVisitor<TResult> typedVisitor = visitor as ISTGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpr_expr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StlangContext stlang() {
		StlangContext _localctx = new StlangContext(Context, State);
		EnterRule(_localctx, 4, RULE_stlang);
		try {
			_localctx = new Expr_exprContext(_localctx);
			EnterOuterAlt(_localctx, 1);
			{
			State = 30; Match(IDENTIFIER);
			State = 31; Match(ASSIGN);
			State = 32; expr(0);
			State = 33; Match(SEMI_COLON);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExprContext : ParserRuleContext {
		public ExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expr; } }
	 
		public ExprContext() { }
		public virtual void CopyFrom(ExprContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class Expr_defineContext : ExprContext {
		public DefineContext define() {
			return GetRuleContext<DefineContext>(0);
		}
		public Expr_defineContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISTGrammerVisitor<TResult> typedVisitor = visitor as ISTGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpr_define(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Expr_additiveContext : ExprContext {
		public ExprContext lhs;
		public IToken op;
		public ExprContext rhs;
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ITerminalNode PLUS() { return GetToken(STGrammerParser.PLUS, 0); }
		public ITerminalNode MINUS() { return GetToken(STGrammerParser.MINUS, 0); }
		public Expr_additiveContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISTGrammerVisitor<TResult> typedVisitor = visitor as ISTGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpr_additive(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExprContext expr() {
		return expr(0);
	}

	private ExprContext expr(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExprContext _localctx = new ExprContext(Context, _parentState);
		ExprContext _prevctx = _localctx;
		int _startState = 6;
		EnterRecursionRule(_localctx, 6, RULE_expr, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			{
			_localctx = new Expr_defineContext(_localctx);
			Context = _localctx;
			_prevctx = _localctx;

			State = 36; define();
			}
			Context.Stop = TokenStream.LT(-1);
			State = 43;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,4,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new Expr_additiveContext(new ExprContext(_parentctx, _parentState));
					((Expr_additiveContext)_localctx).lhs = _prevctx;
					PushNewRecursionContext(_localctx, _startState, RULE_expr);
					State = 38;
					if (!(Precpred(Context, 1))) throw new FailedPredicateException(this, "Precpred(Context, 1)");
					State = 39;
					((Expr_additiveContext)_localctx).op = TokenStream.LT(1);
					_la = TokenStream.LA(1);
					if ( !(_la==PLUS || _la==MINUS) ) {
						((Expr_additiveContext)_localctx).op = ErrorHandler.RecoverInline(this);
					}
					else {
						ErrorHandler.ReportMatch(this);
					    Consume();
					}
					State = 40; ((Expr_additiveContext)_localctx).rhs = expr(2);
					}
					} 
				}
				State = 45;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,4,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class DefineContext : ParserRuleContext {
		public ITerminalNode IDENTIFIER() { return GetToken(STGrammerParser.IDENTIFIER, 0); }
		public DefineContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_define; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISTGrammerVisitor<TResult> typedVisitor = visitor as ISTGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDefine(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DefineContext define() {
		DefineContext _localctx = new DefineContext(Context, State);
		EnterRule(_localctx, 8, RULE_define);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 46; Match(IDENTIFIER);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LinecommentContext : ParserRuleContext {
		public ITerminalNode SINGLE_LINE_COMMENT() { return GetToken(STGrammerParser.SINGLE_LINE_COMMENT, 0); }
		public LinecommentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_linecomment; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISTGrammerVisitor<TResult> typedVisitor = visitor as ISTGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLinecomment(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LinecommentContext linecomment() {
		LinecommentContext _localctx = new LinecommentContext(Context, State);
		EnterRule(_localctx, 10, RULE_linecomment);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 48; Match(SINGLE_LINE_COMMENT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 3: return expr_sempred((ExprContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expr_sempred(ExprContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 1);
		}
		return true;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\x1E', '\x35', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x3', '\x2', '\x5', '\x2', 
		'\x10', '\n', '\x2', '\x3', '\x2', '\a', '\x2', '\x13', '\n', '\x2', '\f', 
		'\x2', '\xE', '\x2', '\x16', '\v', '\x2', '\x3', '\x2', '\x5', '\x2', 
		'\x19', '\n', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', 
		'\x3', '\x5', '\x3', '\x1F', '\n', '\x3', '\x3', '\x4', '\x3', '\x4', 
		'\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\a', '\x5', ',', 
		'\n', '\x5', '\f', '\x5', '\xE', '\x5', '/', '\v', '\x5', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x2', '\x3', '\b', 
		'\b', '\x2', '\x4', '\x6', '\b', '\n', '\f', '\x2', '\x3', '\x3', '\x2', 
		'\x4', '\x5', '\x2', '\x33', '\x2', '\x14', '\x3', '\x2', '\x2', '\x2', 
		'\x4', '\x1E', '\x3', '\x2', '\x2', '\x2', '\x6', ' ', '\x3', '\x2', '\x2', 
		'\x2', '\b', '%', '\x3', '\x2', '\x2', '\x2', '\n', '\x30', '\x3', '\x2', 
		'\x2', '\x2', '\f', '\x32', '\x3', '\x2', '\x2', '\x2', '\xE', '\x10', 
		'\x5', '\x4', '\x3', '\x2', '\xF', '\xE', '\x3', '\x2', '\x2', '\x2', 
		'\xF', '\x10', '\x3', '\x2', '\x2', '\x2', '\x10', '\x11', '\x3', '\x2', 
		'\x2', '\x2', '\x11', '\x13', '\a', '\x3', '\x2', '\x2', '\x12', '\xF', 
		'\x3', '\x2', '\x2', '\x2', '\x13', '\x16', '\x3', '\x2', '\x2', '\x2', 
		'\x14', '\x12', '\x3', '\x2', '\x2', '\x2', '\x14', '\x15', '\x3', '\x2', 
		'\x2', '\x2', '\x15', '\x18', '\x3', '\x2', '\x2', '\x2', '\x16', '\x14', 
		'\x3', '\x2', '\x2', '\x2', '\x17', '\x19', '\x5', '\x4', '\x3', '\x2', 
		'\x18', '\x17', '\x3', '\x2', '\x2', '\x2', '\x18', '\x19', '\x3', '\x2', 
		'\x2', '\x2', '\x19', '\x1A', '\x3', '\x2', '\x2', '\x2', '\x1A', '\x1B', 
		'\a', '\x2', '\x2', '\x3', '\x1B', '\x3', '\x3', '\x2', '\x2', '\x2', 
		'\x1C', '\x1F', '\x5', '\x6', '\x4', '\x2', '\x1D', '\x1F', '\x5', '\f', 
		'\a', '\x2', '\x1E', '\x1C', '\x3', '\x2', '\x2', '\x2', '\x1E', '\x1D', 
		'\x3', '\x2', '\x2', '\x2', '\x1F', '\x5', '\x3', '\x2', '\x2', '\x2', 
		' ', '!', '\a', '\x1C', '\x2', '\x2', '!', '\"', '\a', '\xF', '\x2', '\x2', 
		'\"', '#', '\x5', '\b', '\x5', '\x2', '#', '$', '\a', '\x15', '\x2', '\x2', 
		'$', '\a', '\x3', '\x2', '\x2', '\x2', '%', '&', '\b', '\x5', '\x1', '\x2', 
		'&', '\'', '\x5', '\n', '\x6', '\x2', '\'', '-', '\x3', '\x2', '\x2', 
		'\x2', '(', ')', '\f', '\x3', '\x2', '\x2', ')', '*', '\t', '\x2', '\x2', 
		'\x2', '*', ',', '\x5', '\b', '\x5', '\x4', '+', '(', '\x3', '\x2', '\x2', 
		'\x2', ',', '/', '\x3', '\x2', '\x2', '\x2', '-', '+', '\x3', '\x2', '\x2', 
		'\x2', '-', '.', '\x3', '\x2', '\x2', '\x2', '.', '\t', '\x3', '\x2', 
		'\x2', '\x2', '/', '-', '\x3', '\x2', '\x2', '\x2', '\x30', '\x31', '\a', 
		'\x1C', '\x2', '\x2', '\x31', '\v', '\x3', '\x2', '\x2', '\x2', '\x32', 
		'\x33', '\a', '\x1E', '\x2', '\x2', '\x33', '\r', '\x3', '\x2', '\x2', 
		'\x2', '\a', '\xF', '\x14', '\x18', '\x1E', '-',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
