//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/takuumi/Projects/StudyANTLR/Part3/STtoKVScript/STGrammer.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="STGrammerParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface ISTGrammerVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="STGrammerParser.input"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInput([NotNull] STGrammerParser.InputContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expr_stlang</c>
	/// labeled alternative in <see cref="STGrammerParser.oneline"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr_stlang([NotNull] STGrammerParser.Expr_stlangContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expr_stlinecomment</c>
	/// labeled alternative in <see cref="STGrammerParser.oneline"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr_stlinecomment([NotNull] STGrammerParser.Expr_stlinecommentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STGrammerParser.stlang"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStlang([NotNull] STGrammerParser.StlangContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expr_define</c>
	/// labeled alternative in <see cref="STGrammerParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr_define([NotNull] STGrammerParser.Expr_defineContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expr_additive</c>
	/// labeled alternative in <see cref="STGrammerParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr_additive([NotNull] STGrammerParser.Expr_additiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STGrammerParser.define"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefine([NotNull] STGrammerParser.DefineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STGrammerParser.linecomment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLinecomment([NotNull] STGrammerParser.LinecommentContext context);
}
