//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/takuumi/Projects/StudyANTLR/Part3/STtoKVScript/STGrammer.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class STGrammerParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		PLUS=1, MINUS=2, ASTERISK=3, SLASH=4, POW=5, LT=6, GT=7, LE=8, GE=9, EQ=10, 
		NEQ=11, ASSIGN=12, OUTREF=13, RANGE=14, COMMA=15, OPEN_PAREN=16, CLOSE_PAREN=17, 
		SEMI_COLON=18, COLON=19, NOT=20, MOD=21, AND=22, OR=23, XOR=24, AND2=25, 
		CASE=26, OF=27, END_CASE=28, REPEAT=29, UNTIL=30, ELSE=31, RETURN=32, 
		END_REPEAT=33, EXIT=34, MULTISTRING=35, WIDESTRING=36, WS=37, SINGLE_LINE_COMMENT=38, 
		NUM_UINT=39, NUM_REAL=40, TYPE_INT=41, TYPE_UINT=42, TYPE_LREAL=43, TYPE_STRING=44, 
		DISP_BIN=45, DISP_OCT=46, DISP_HEX=47, IDENTIFIER=48;
	public const int
		RULE_input = 0, RULE_block = 1, RULE_statement_repeat = 2, RULE_statement_return = 3, 
		RULE_statement_case = 4, RULE_case_of_state = 5, RULE_expr = 6, RULE_func_expr = 7, 
		RULE_variable = 8, RULE_keyword = 9, RULE_normal_value = 10, RULE_type_define = 11, 
		RULE_disp_define = 12, RULE_linecomment = 13;
	public static readonly string[] ruleNames = {
		"input", "block", "statement_repeat", "statement_return", "statement_case", 
		"case_of_state", "expr", "func_expr", "variable", "keyword", "normal_value", 
		"type_define", "disp_define", "linecomment"
	};

	private static readonly string[] _LiteralNames = {
		null, "'+'", "'-'", "'*'", "'/'", "'**'", "'<'", "'>'", "'<='", "'>='", 
		"'='", "'<>'", "':='", "'=>'", "'..'", "','", "'('", "')'", "';'", "':'", 
		null, null, null, null, null, "'&'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "PLUS", "MINUS", "ASTERISK", "SLASH", "POW", "LT", "GT", "LE", "GE", 
		"EQ", "NEQ", "ASSIGN", "OUTREF", "RANGE", "COMMA", "OPEN_PAREN", "CLOSE_PAREN", 
		"SEMI_COLON", "COLON", "NOT", "MOD", "AND", "OR", "XOR", "AND2", "CASE", 
		"OF", "END_CASE", "REPEAT", "UNTIL", "ELSE", "RETURN", "END_REPEAT", "EXIT", 
		"MULTISTRING", "WIDESTRING", "WS", "SINGLE_LINE_COMMENT", "NUM_UINT", 
		"NUM_REAL", "TYPE_INT", "TYPE_UINT", "TYPE_LREAL", "TYPE_STRING", "DISP_BIN", 
		"DISP_OCT", "DISP_HEX", "IDENTIFIER"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "STGrammer.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static STGrammerParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public STGrammerParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public STGrammerParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class InputContext : ParserRuleContext {
		public ITerminalNode Eof() { return GetToken(STGrammerParser.Eof, 0); }
		public BlockContext[] block() {
			return GetRuleContexts<BlockContext>();
		}
		public BlockContext block(int i) {
			return GetRuleContext<BlockContext>(i);
		}
		public InputContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_input; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISTGrammerVisitor<TResult> typedVisitor = visitor as ISTGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInput(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public InputContext input() {
		InputContext _localctx = new InputContext(Context, State);
		EnterRule(_localctx, 0, RULE_input);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 31;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << PLUS) | (1L << MINUS) | (1L << NOT) | (1L << CASE) | (1L << REPEAT) | (1L << RETURN) | (1L << EXIT) | (1L << MULTISTRING) | (1L << WIDESTRING) | (1L << SINGLE_LINE_COMMENT) | (1L << NUM_UINT) | (1L << NUM_REAL) | (1L << TYPE_INT) | (1L << TYPE_UINT) | (1L << TYPE_LREAL) | (1L << TYPE_STRING) | (1L << DISP_BIN) | (1L << DISP_OCT) | (1L << DISP_HEX) | (1L << IDENTIFIER))) != 0)) {
				{
				{
				State = 28; block();
				}
				}
				State = 33;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 34; Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BlockContext : ParserRuleContext {
		public BlockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_block; } }
	 
		public BlockContext() { }
		public virtual void CopyFrom(BlockContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class St_state_repeatContext : BlockContext {
		public Statement_repeatContext statement_repeat() {
			return GetRuleContext<Statement_repeatContext>(0);
		}
		public St_state_repeatContext(BlockContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISTGrammerVisitor<TResult> typedVisitor = visitor as ISTGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSt_state_repeat(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class St_linecommentContext : BlockContext {
		public LinecommentContext linecomment() {
			return GetRuleContext<LinecommentContext>(0);
		}
		public St_linecommentContext(BlockContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISTGrammerVisitor<TResult> typedVisitor = visitor as ISTGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSt_linecomment(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class St_expressionContext : BlockContext {
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ITerminalNode SEMI_COLON() { return GetToken(STGrammerParser.SEMI_COLON, 0); }
		public St_expressionContext(BlockContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISTGrammerVisitor<TResult> typedVisitor = visitor as ISTGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSt_expression(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class St_state_returnContext : BlockContext {
		public Statement_returnContext statement_return() {
			return GetRuleContext<Statement_returnContext>(0);
		}
		public St_state_returnContext(BlockContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISTGrammerVisitor<TResult> typedVisitor = visitor as ISTGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSt_state_return(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class St_state_caseContext : BlockContext {
		public Statement_caseContext statement_case() {
			return GetRuleContext<Statement_caseContext>(0);
		}
		public St_state_caseContext(BlockContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISTGrammerVisitor<TResult> typedVisitor = visitor as ISTGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSt_state_case(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BlockContext block() {
		BlockContext _localctx = new BlockContext(Context, State);
		EnterRule(_localctx, 2, RULE_block);
		try {
			State = 43;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case REPEAT:
				_localctx = new St_state_repeatContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 36; statement_repeat();
				}
				break;
			case RETURN:
				_localctx = new St_state_returnContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 37; statement_return();
				}
				break;
			case CASE:
				_localctx = new St_state_caseContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 38; statement_case();
				}
				break;
			case PLUS:
			case MINUS:
			case NOT:
			case EXIT:
			case MULTISTRING:
			case WIDESTRING:
			case NUM_UINT:
			case NUM_REAL:
			case TYPE_INT:
			case TYPE_UINT:
			case TYPE_LREAL:
			case TYPE_STRING:
			case DISP_BIN:
			case DISP_OCT:
			case DISP_HEX:
			case IDENTIFIER:
				_localctx = new St_expressionContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 39; expr(0);
				State = 40; Match(SEMI_COLON);
				}
				break;
			case SINGLE_LINE_COMMENT:
				_localctx = new St_linecommentContext(_localctx);
				EnterOuterAlt(_localctx, 5);
				{
				State = 42; linecomment();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Statement_repeatContext : ParserRuleContext {
		public Statement_repeatContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement_repeat; } }
	 
		public Statement_repeatContext() { }
		public virtual void CopyFrom(Statement_repeatContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class Expt_stblock_repeatContext : Statement_repeatContext {
		public BlockContext _block;
		public IList<BlockContext> _blks = new List<BlockContext>();
		public ITerminalNode REPEAT() { return GetToken(STGrammerParser.REPEAT, 0); }
		public ITerminalNode UNTIL() { return GetToken(STGrammerParser.UNTIL, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ITerminalNode END_REPEAT() { return GetToken(STGrammerParser.END_REPEAT, 0); }
		public ITerminalNode SEMI_COLON() { return GetToken(STGrammerParser.SEMI_COLON, 0); }
		public BlockContext[] block() {
			return GetRuleContexts<BlockContext>();
		}
		public BlockContext block(int i) {
			return GetRuleContext<BlockContext>(i);
		}
		public Expt_stblock_repeatContext(Statement_repeatContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISTGrammerVisitor<TResult> typedVisitor = visitor as ISTGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpt_stblock_repeat(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Statement_repeatContext statement_repeat() {
		Statement_repeatContext _localctx = new Statement_repeatContext(Context, State);
		EnterRule(_localctx, 4, RULE_statement_repeat);
		int _la;
		try {
			_localctx = new Expt_stblock_repeatContext(_localctx);
			EnterOuterAlt(_localctx, 1);
			{
			State = 45; Match(REPEAT);
			State = 49;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << PLUS) | (1L << MINUS) | (1L << NOT) | (1L << CASE) | (1L << REPEAT) | (1L << RETURN) | (1L << EXIT) | (1L << MULTISTRING) | (1L << WIDESTRING) | (1L << SINGLE_LINE_COMMENT) | (1L << NUM_UINT) | (1L << NUM_REAL) | (1L << TYPE_INT) | (1L << TYPE_UINT) | (1L << TYPE_LREAL) | (1L << TYPE_STRING) | (1L << DISP_BIN) | (1L << DISP_OCT) | (1L << DISP_HEX) | (1L << IDENTIFIER))) != 0)) {
				{
				{
				State = 46; ((Expt_stblock_repeatContext)_localctx)._block = block();
				((Expt_stblock_repeatContext)_localctx)._blks.Add(((Expt_stblock_repeatContext)_localctx)._block);
				}
				}
				State = 51;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 52; Match(UNTIL);
			State = 53; expr(0);
			State = 54; Match(END_REPEAT);
			State = 55; Match(SEMI_COLON);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Statement_returnContext : ParserRuleContext {
		public ITerminalNode RETURN() { return GetToken(STGrammerParser.RETURN, 0); }
		public ITerminalNode SEMI_COLON() { return GetToken(STGrammerParser.SEMI_COLON, 0); }
		public Statement_returnContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement_return; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISTGrammerVisitor<TResult> typedVisitor = visitor as ISTGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStatement_return(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Statement_returnContext statement_return() {
		Statement_returnContext _localctx = new Statement_returnContext(Context, State);
		EnterRule(_localctx, 6, RULE_statement_return);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 57; Match(RETURN);
			State = 58; Match(SEMI_COLON);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Statement_caseContext : ParserRuleContext {
		public Statement_caseContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement_case; } }
	 
		public Statement_caseContext() { }
		public virtual void CopyFrom(Statement_caseContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class St_case_detailContext : Statement_caseContext {
		public Case_of_stateContext _case_of_state;
		public IList<Case_of_stateContext> _caseState = new List<Case_of_stateContext>();
		public BlockContext _block;
		public IList<BlockContext> _blks = new List<BlockContext>();
		public IList<BlockContext> _else_blks = new List<BlockContext>();
		public ITerminalNode CASE() { return GetToken(STGrammerParser.CASE, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ITerminalNode OF() { return GetToken(STGrammerParser.OF, 0); }
		public ITerminalNode END_CASE() { return GetToken(STGrammerParser.END_CASE, 0); }
		public ITerminalNode SEMI_COLON() { return GetToken(STGrammerParser.SEMI_COLON, 0); }
		public ITerminalNode[] COLON() { return GetTokens(STGrammerParser.COLON); }
		public ITerminalNode COLON(int i) {
			return GetToken(STGrammerParser.COLON, i);
		}
		public ITerminalNode ELSE() { return GetToken(STGrammerParser.ELSE, 0); }
		public Case_of_stateContext[] case_of_state() {
			return GetRuleContexts<Case_of_stateContext>();
		}
		public Case_of_stateContext case_of_state(int i) {
			return GetRuleContext<Case_of_stateContext>(i);
		}
		public BlockContext[] block() {
			return GetRuleContexts<BlockContext>();
		}
		public BlockContext block(int i) {
			return GetRuleContext<BlockContext>(i);
		}
		public St_case_detailContext(Statement_caseContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISTGrammerVisitor<TResult> typedVisitor = visitor as ISTGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSt_case_detail(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Statement_caseContext statement_case() {
		Statement_caseContext _localctx = new Statement_caseContext(Context, State);
		EnterRule(_localctx, 8, RULE_statement_case);
		int _la;
		try {
			int _alt;
			_localctx = new St_case_detailContext(_localctx);
			EnterOuterAlt(_localctx, 1);
			{
			State = 60; Match(CASE);
			State = 61; expr(0);
			State = 62; Match(OF);
			State = 77;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << RANGE) | (1L << COMMA) | (1L << IDENTIFIER))) != 0)) {
				{
				{
				State = 64;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				do {
					{
					{
					State = 63; ((St_case_detailContext)_localctx)._case_of_state = case_of_state();
					((St_case_detailContext)_localctx)._caseState.Add(((St_case_detailContext)_localctx)._case_of_state);
					}
					}
					State = 66;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << RANGE) | (1L << COMMA) | (1L << IDENTIFIER))) != 0) );
				State = 68; Match(COLON);
				State = 72;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,4,Context);
				while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
					if ( _alt==1 ) {
						{
						{
						State = 69; ((St_case_detailContext)_localctx)._block = block();
						((St_case_detailContext)_localctx)._blks.Add(((St_case_detailContext)_localctx)._block);
						}
						} 
					}
					State = 74;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,4,Context);
				}
				}
				}
				State = 79;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 87;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==ELSE) {
				{
				State = 80; Match(ELSE);
				State = 84;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << PLUS) | (1L << MINUS) | (1L << NOT) | (1L << CASE) | (1L << REPEAT) | (1L << RETURN) | (1L << EXIT) | (1L << MULTISTRING) | (1L << WIDESTRING) | (1L << SINGLE_LINE_COMMENT) | (1L << NUM_UINT) | (1L << NUM_REAL) | (1L << TYPE_INT) | (1L << TYPE_UINT) | (1L << TYPE_LREAL) | (1L << TYPE_STRING) | (1L << DISP_BIN) | (1L << DISP_OCT) | (1L << DISP_HEX) | (1L << IDENTIFIER))) != 0)) {
					{
					{
					State = 81; ((St_case_detailContext)_localctx)._block = block();
					((St_case_detailContext)_localctx)._else_blks.Add(((St_case_detailContext)_localctx)._block);
					}
					}
					State = 86;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			State = 89; Match(END_CASE);
			State = 90; Match(SEMI_COLON);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Case_of_stateContext : ParserRuleContext {
		public ITerminalNode IDENTIFIER() { return GetToken(STGrammerParser.IDENTIFIER, 0); }
		public ITerminalNode COMMA() { return GetToken(STGrammerParser.COMMA, 0); }
		public ITerminalNode RANGE() { return GetToken(STGrammerParser.RANGE, 0); }
		public Case_of_stateContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_case_of_state; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISTGrammerVisitor<TResult> typedVisitor = visitor as ISTGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCase_of_state(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Case_of_stateContext case_of_state() {
		Case_of_stateContext _localctx = new Case_of_stateContext(Context, State);
		EnterRule(_localctx, 10, RULE_case_of_state);
		try {
			State = 97;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case IDENTIFIER:
				EnterOuterAlt(_localctx, 1);
				{
				State = 92; Match(IDENTIFIER);
				}
				break;
			case COMMA:
				EnterOuterAlt(_localctx, 2);
				{
				State = 93; Match(COMMA);
				State = 94; Match(IDENTIFIER);
				}
				break;
			case RANGE:
				EnterOuterAlt(_localctx, 3);
				{
				State = 95; Match(RANGE);
				State = 96; Match(IDENTIFIER);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExprContext : ParserRuleContext {
		public ExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expr; } }
	 
		public ExprContext() { }
		public virtual void CopyFrom(ExprContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class Expr_variableContext : ExprContext {
		public VariableContext variable() {
			return GetRuleContext<VariableContext>(0);
		}
		public Expr_variableContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISTGrammerVisitor<TResult> typedVisitor = visitor as ISTGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpr_variable(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Expr_widestringContext : ExprContext {
		public ITerminalNode[] WIDESTRING() { return GetTokens(STGrammerParser.WIDESTRING); }
		public ITerminalNode WIDESTRING(int i) {
			return GetToken(STGrammerParser.WIDESTRING, i);
		}
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public Expr_widestringContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISTGrammerVisitor<TResult> typedVisitor = visitor as ISTGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpr_widestring(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Expr_logical_operationContext : ExprContext {
		public ExprContext lhs;
		public IToken op;
		public ExprContext rhs;
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ITerminalNode AND() { return GetToken(STGrammerParser.AND, 0); }
		public ITerminalNode AND2() { return GetToken(STGrammerParser.AND2, 0); }
		public ITerminalNode OR() { return GetToken(STGrammerParser.OR, 0); }
		public ITerminalNode XOR() { return GetToken(STGrammerParser.XOR, 0); }
		public Expr_logical_operationContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISTGrammerVisitor<TResult> typedVisitor = visitor as ISTGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpr_logical_operation(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Expr_assignContext : ExprContext {
		public ExprContext lhs;
		public ExprContext rhs;
		public ITerminalNode ASSIGN() { return GetToken(STGrammerParser.ASSIGN, 0); }
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public Expr_assignContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISTGrammerVisitor<TResult> typedVisitor = visitor as ISTGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpr_assign(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Expr_funccallContext : ExprContext {
		public IToken funcname;
		public Func_exprContext _func_expr;
		public IList<Func_exprContext> _args = new List<Func_exprContext>();
		public IList<Func_exprContext> _args2 = new List<Func_exprContext>();
		public ITerminalNode OPEN_PAREN() { return GetToken(STGrammerParser.OPEN_PAREN, 0); }
		public ITerminalNode CLOSE_PAREN() { return GetToken(STGrammerParser.CLOSE_PAREN, 0); }
		public ITerminalNode IDENTIFIER() { return GetToken(STGrammerParser.IDENTIFIER, 0); }
		public ITerminalNode[] COMMA() { return GetTokens(STGrammerParser.COMMA); }
		public ITerminalNode COMMA(int i) {
			return GetToken(STGrammerParser.COMMA, i);
		}
		public Func_exprContext[] func_expr() {
			return GetRuleContexts<Func_exprContext>();
		}
		public Func_exprContext func_expr(int i) {
			return GetRuleContext<Func_exprContext>(i);
		}
		public Expr_funccallContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISTGrammerVisitor<TResult> typedVisitor = visitor as ISTGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpr_funccall(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Expr_multipricativeContext : ExprContext {
		public ExprContext lhs;
		public IToken op;
		public ExprContext rhs;
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ITerminalNode ASTERISK() { return GetToken(STGrammerParser.ASTERISK, 0); }
		public ITerminalNode SLASH() { return GetToken(STGrammerParser.SLASH, 0); }
		public ITerminalNode POW() { return GetToken(STGrammerParser.POW, 0); }
		public ITerminalNode MOD() { return GetToken(STGrammerParser.MOD, 0); }
		public Expr_multipricativeContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISTGrammerVisitor<TResult> typedVisitor = visitor as ISTGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpr_multipricative(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Expr_multistringContext : ExprContext {
		public ITerminalNode[] MULTISTRING() { return GetTokens(STGrammerParser.MULTISTRING); }
		public ITerminalNode MULTISTRING(int i) {
			return GetToken(STGrammerParser.MULTISTRING, i);
		}
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public Expr_multistringContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISTGrammerVisitor<TResult> typedVisitor = visitor as ISTGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpr_multistring(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Expr_typedefineContext : ExprContext {
		public Type_defineContext type_define() {
			return GetRuleContext<Type_defineContext>(0);
		}
		public Expr_typedefineContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISTGrammerVisitor<TResult> typedVisitor = visitor as ISTGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpr_typedefine(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Expr_outrefContext : ExprContext {
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ITerminalNode OUTREF() { return GetToken(STGrammerParser.OUTREF, 0); }
		public Expr_outrefContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISTGrammerVisitor<TResult> typedVisitor = visitor as ISTGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpr_outref(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Expr_additiveContext : ExprContext {
		public ExprContext lhs;
		public IToken op;
		public ExprContext rhs;
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ITerminalNode PLUS() { return GetToken(STGrammerParser.PLUS, 0); }
		public ITerminalNode MINUS() { return GetToken(STGrammerParser.MINUS, 0); }
		public Expr_additiveContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISTGrammerVisitor<TResult> typedVisitor = visitor as ISTGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpr_additive(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Expr_keywordContext : ExprContext {
		public KeywordContext keyword() {
			return GetRuleContext<KeywordContext>(0);
		}
		public Expr_keywordContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISTGrammerVisitor<TResult> typedVisitor = visitor as ISTGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpr_keyword(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Expr_normal_valueContext : ExprContext {
		public Normal_valueContext normal_value() {
			return GetRuleContext<Normal_valueContext>(0);
		}
		public Expr_normal_valueContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISTGrammerVisitor<TResult> typedVisitor = visitor as ISTGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpr_normal_value(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Expr_equivalent_operationContext : ExprContext {
		public ExprContext lhs;
		public IToken op;
		public ExprContext rhs;
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ITerminalNode EQ() { return GetToken(STGrammerParser.EQ, 0); }
		public ITerminalNode NEQ() { return GetToken(STGrammerParser.NEQ, 0); }
		public Expr_equivalent_operationContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISTGrammerVisitor<TResult> typedVisitor = visitor as ISTGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpr_equivalent_operation(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Expr_unaryContext : ExprContext {
		public IToken op;
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ITerminalNode PLUS() { return GetToken(STGrammerParser.PLUS, 0); }
		public ITerminalNode MINUS() { return GetToken(STGrammerParser.MINUS, 0); }
		public Expr_unaryContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISTGrammerVisitor<TResult> typedVisitor = visitor as ISTGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpr_unary(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Expr_notContext : ExprContext {
		public ITerminalNode NOT() { return GetToken(STGrammerParser.NOT, 0); }
		public Func_exprContext func_expr() {
			return GetRuleContext<Func_exprContext>(0);
		}
		public Expr_notContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISTGrammerVisitor<TResult> typedVisitor = visitor as ISTGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpr_not(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Expr_dispdefineContext : ExprContext {
		public Disp_defineContext disp_define() {
			return GetRuleContext<Disp_defineContext>(0);
		}
		public Expr_dispdefineContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISTGrammerVisitor<TResult> typedVisitor = visitor as ISTGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpr_dispdefine(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Expr_comparison_operationContext : ExprContext {
		public ExprContext lhs;
		public IToken op;
		public ExprContext rhs;
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ITerminalNode GT() { return GetToken(STGrammerParser.GT, 0); }
		public ITerminalNode LT() { return GetToken(STGrammerParser.LT, 0); }
		public ITerminalNode GE() { return GetToken(STGrammerParser.GE, 0); }
		public ITerminalNode LE() { return GetToken(STGrammerParser.LE, 0); }
		public Expr_comparison_operationContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISTGrammerVisitor<TResult> typedVisitor = visitor as ISTGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpr_comparison_operation(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExprContext expr() {
		return expr(0);
	}

	private ExprContext expr(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExprContext _localctx = new ExprContext(Context, _parentState);
		ExprContext _prevctx = _localctx;
		int _startState = 12;
		EnterRecursionRule(_localctx, 12, RULE_expr, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 133;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,11,Context) ) {
			case 1:
				{
				_localctx = new Expr_unaryContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 100;
				((Expr_unaryContext)_localctx).op = TokenStream.LT(1);
				_la = TokenStream.LA(1);
				if ( !(_la==PLUS || _la==MINUS) ) {
					((Expr_unaryContext)_localctx).op = ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 101; expr(17);
				}
				break;
			case 2:
				{
				_localctx = new Expr_notContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 102; Match(NOT);
				State = 103; func_expr();
				}
				break;
			case 3:
				{
				_localctx = new Expr_funccallContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 104; ((Expr_funccallContext)_localctx).funcname = Match(IDENTIFIER);
				State = 105; Match(OPEN_PAREN);
				State = 109;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << PLUS) | (1L << MINUS) | (1L << NOT) | (1L << EXIT) | (1L << MULTISTRING) | (1L << WIDESTRING) | (1L << NUM_UINT) | (1L << NUM_REAL) | (1L << TYPE_INT) | (1L << TYPE_UINT) | (1L << TYPE_LREAL) | (1L << TYPE_STRING) | (1L << DISP_BIN) | (1L << DISP_OCT) | (1L << DISP_HEX) | (1L << IDENTIFIER))) != 0)) {
					{
					{
					State = 106; ((Expr_funccallContext)_localctx)._func_expr = func_expr();
					((Expr_funccallContext)_localctx)._args.Add(((Expr_funccallContext)_localctx)._func_expr);
					}
					}
					State = 111;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 116;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==COMMA) {
					{
					{
					State = 112; Match(COMMA);
					State = 113; ((Expr_funccallContext)_localctx)._func_expr = func_expr();
					((Expr_funccallContext)_localctx)._args2.Add(((Expr_funccallContext)_localctx)._func_expr);
					}
					}
					State = 118;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 119; Match(CLOSE_PAREN);
				}
				break;
			case 4:
				{
				_localctx = new Expr_multistringContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 120; Match(MULTISTRING);
				State = 121; expr(0);
				State = 122; Match(MULTISTRING);
				}
				break;
			case 5:
				{
				_localctx = new Expr_widestringContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 124; Match(WIDESTRING);
				State = 125; expr(0);
				State = 126; Match(WIDESTRING);
				}
				break;
			case 6:
				{
				_localctx = new Expr_keywordContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 128; keyword();
				}
				break;
			case 7:
				{
				_localctx = new Expr_typedefineContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 129; type_define();
				}
				break;
			case 8:
				{
				_localctx = new Expr_dispdefineContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 130; disp_define();
				}
				break;
			case 9:
				{
				_localctx = new Expr_normal_valueContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 131; normal_value();
				}
				break;
			case 10:
				{
				_localctx = new Expr_variableContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 132; variable();
				}
				break;
			}
			Context.Stop = TokenStream.LT(-1);
			State = 158;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,13,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 156;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,12,Context) ) {
					case 1:
						{
						_localctx = new Expr_additiveContext(new ExprContext(_parentctx, _parentState));
						((Expr_additiveContext)_localctx).lhs = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 135;
						if (!(Precpred(Context, 15))) throw new FailedPredicateException(this, "Precpred(Context, 15)");
						State = 136;
						((Expr_additiveContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !(_la==PLUS || _la==MINUS) ) {
							((Expr_additiveContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 137; ((Expr_additiveContext)_localctx).rhs = expr(16);
						}
						break;
					case 2:
						{
						_localctx = new Expr_multipricativeContext(new ExprContext(_parentctx, _parentState));
						((Expr_multipricativeContext)_localctx).lhs = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 138;
						if (!(Precpred(Context, 14))) throw new FailedPredicateException(this, "Precpred(Context, 14)");
						State = 139;
						((Expr_multipricativeContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << ASTERISK) | (1L << SLASH) | (1L << POW) | (1L << MOD))) != 0)) ) {
							((Expr_multipricativeContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 140; ((Expr_multipricativeContext)_localctx).rhs = expr(15);
						}
						break;
					case 3:
						{
						_localctx = new Expr_logical_operationContext(new ExprContext(_parentctx, _parentState));
						((Expr_logical_operationContext)_localctx).lhs = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 141;
						if (!(Precpred(Context, 13))) throw new FailedPredicateException(this, "Precpred(Context, 13)");
						State = 142;
						((Expr_logical_operationContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << AND) | (1L << OR) | (1L << XOR) | (1L << AND2))) != 0)) ) {
							((Expr_logical_operationContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 143; ((Expr_logical_operationContext)_localctx).rhs = expr(14);
						}
						break;
					case 4:
						{
						_localctx = new Expr_comparison_operationContext(new ExprContext(_parentctx, _parentState));
						((Expr_comparison_operationContext)_localctx).lhs = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 144;
						if (!(Precpred(Context, 12))) throw new FailedPredicateException(this, "Precpred(Context, 12)");
						State = 145;
						((Expr_comparison_operationContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << LT) | (1L << GT) | (1L << LE) | (1L << GE))) != 0)) ) {
							((Expr_comparison_operationContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 146; ((Expr_comparison_operationContext)_localctx).rhs = expr(13);
						}
						break;
					case 5:
						{
						_localctx = new Expr_equivalent_operationContext(new ExprContext(_parentctx, _parentState));
						((Expr_equivalent_operationContext)_localctx).lhs = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 147;
						if (!(Precpred(Context, 11))) throw new FailedPredicateException(this, "Precpred(Context, 11)");
						State = 148;
						((Expr_equivalent_operationContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !(_la==EQ || _la==NEQ) ) {
							((Expr_equivalent_operationContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 149; ((Expr_equivalent_operationContext)_localctx).rhs = expr(12);
						}
						break;
					case 6:
						{
						_localctx = new Expr_assignContext(new ExprContext(_parentctx, _parentState));
						((Expr_assignContext)_localctx).lhs = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 150;
						if (!(Precpred(Context, 10))) throw new FailedPredicateException(this, "Precpred(Context, 10)");
						State = 151; Match(ASSIGN);
						State = 152; ((Expr_assignContext)_localctx).rhs = expr(11);
						}
						break;
					case 7:
						{
						_localctx = new Expr_outrefContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 153;
						if (!(Precpred(Context, 9))) throw new FailedPredicateException(this, "Precpred(Context, 9)");
						State = 154; Match(OUTREF);
						State = 155; expr(10);
						}
						break;
					}
					} 
				}
				State = 160;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,13,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class Func_exprContext : ParserRuleContext {
		public Func_exprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_func_expr; } }
	 
		public Func_exprContext() { }
		public virtual void CopyFrom(Func_exprContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class Func_named_argContext : Func_exprContext {
		public ExprContext lhs;
		public IToken op;
		public ExprContext rhs;
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ITerminalNode ASSIGN() { return GetToken(STGrammerParser.ASSIGN, 0); }
		public ITerminalNode OUTREF() { return GetToken(STGrammerParser.OUTREF, 0); }
		public Func_named_argContext(Func_exprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISTGrammerVisitor<TResult> typedVisitor = visitor as ISTGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunc_named_arg(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Func_variableContext : Func_exprContext {
		public VariableContext variable() {
			return GetRuleContext<VariableContext>(0);
		}
		public Func_variableContext(Func_exprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISTGrammerVisitor<TResult> typedVisitor = visitor as ISTGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunc_variable(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Func_operationContext : Func_exprContext {
		public ExprContext lhs;
		public IToken op;
		public ExprContext rhs;
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ITerminalNode AND() { return GetToken(STGrammerParser.AND, 0); }
		public ITerminalNode AND2() { return GetToken(STGrammerParser.AND2, 0); }
		public ITerminalNode OR() { return GetToken(STGrammerParser.OR, 0); }
		public ITerminalNode XOR() { return GetToken(STGrammerParser.XOR, 0); }
		public ITerminalNode GT() { return GetToken(STGrammerParser.GT, 0); }
		public ITerminalNode LT() { return GetToken(STGrammerParser.LT, 0); }
		public ITerminalNode GE() { return GetToken(STGrammerParser.GE, 0); }
		public ITerminalNode LE() { return GetToken(STGrammerParser.LE, 0); }
		public ITerminalNode EQ() { return GetToken(STGrammerParser.EQ, 0); }
		public ITerminalNode NEQ() { return GetToken(STGrammerParser.NEQ, 0); }
		public Func_operationContext(Func_exprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISTGrammerVisitor<TResult> typedVisitor = visitor as ISTGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunc_operation(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Func_exprContext func_expr() {
		Func_exprContext _localctx = new Func_exprContext(Context, State);
		EnterRule(_localctx, 14, RULE_func_expr);
		int _la;
		try {
			State = 170;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,14,Context) ) {
			case 1:
				_localctx = new Func_named_argContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 161; ((Func_named_argContext)_localctx).lhs = expr(0);
				State = 162;
				((Func_named_argContext)_localctx).op = TokenStream.LT(1);
				_la = TokenStream.LA(1);
				if ( !(_la==ASSIGN || _la==OUTREF) ) {
					((Func_named_argContext)_localctx).op = ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 163; ((Func_named_argContext)_localctx).rhs = expr(0);
				}
				break;
			case 2:
				_localctx = new Func_operationContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 165; ((Func_operationContext)_localctx).lhs = expr(0);
				State = 166;
				((Func_operationContext)_localctx).op = TokenStream.LT(1);
				_la = TokenStream.LA(1);
				if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << LT) | (1L << GT) | (1L << LE) | (1L << GE) | (1L << EQ) | (1L << NEQ) | (1L << AND) | (1L << OR) | (1L << XOR) | (1L << AND2))) != 0)) ) {
					((Func_operationContext)_localctx).op = ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 167; ((Func_operationContext)_localctx).rhs = expr(0);
				}
				break;
			case 3:
				_localctx = new Func_variableContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 169; variable();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VariableContext : ParserRuleContext {
		public ITerminalNode IDENTIFIER() { return GetToken(STGrammerParser.IDENTIFIER, 0); }
		public VariableContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_variable; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISTGrammerVisitor<TResult> typedVisitor = visitor as ISTGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVariable(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public VariableContext variable() {
		VariableContext _localctx = new VariableContext(Context, State);
		EnterRule(_localctx, 16, RULE_variable);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 172; Match(IDENTIFIER);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class KeywordContext : ParserRuleContext {
		public ITerminalNode EXIT() { return GetToken(STGrammerParser.EXIT, 0); }
		public KeywordContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_keyword; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISTGrammerVisitor<TResult> typedVisitor = visitor as ISTGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitKeyword(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public KeywordContext keyword() {
		KeywordContext _localctx = new KeywordContext(Context, State);
		EnterRule(_localctx, 18, RULE_keyword);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 174; Match(EXIT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Normal_valueContext : ParserRuleContext {
		public ITerminalNode NUM_UINT() { return GetToken(STGrammerParser.NUM_UINT, 0); }
		public ITerminalNode NUM_REAL() { return GetToken(STGrammerParser.NUM_REAL, 0); }
		public Normal_valueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_normal_value; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISTGrammerVisitor<TResult> typedVisitor = visitor as ISTGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNormal_value(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Normal_valueContext normal_value() {
		Normal_valueContext _localctx = new Normal_valueContext(Context, State);
		EnterRule(_localctx, 20, RULE_normal_value);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 176;
			_la = TokenStream.LA(1);
			if ( !(_la==NUM_UINT || _la==NUM_REAL) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Type_defineContext : ParserRuleContext {
		public ITerminalNode TYPE_INT() { return GetToken(STGrammerParser.TYPE_INT, 0); }
		public ITerminalNode NUM_UINT() { return GetToken(STGrammerParser.NUM_UINT, 0); }
		public ITerminalNode TYPE_UINT() { return GetToken(STGrammerParser.TYPE_UINT, 0); }
		public ITerminalNode TYPE_LREAL() { return GetToken(STGrammerParser.TYPE_LREAL, 0); }
		public ITerminalNode NUM_REAL() { return GetToken(STGrammerParser.NUM_REAL, 0); }
		public ITerminalNode TYPE_STRING() { return GetToken(STGrammerParser.TYPE_STRING, 0); }
		public ITerminalNode[] MULTISTRING() { return GetTokens(STGrammerParser.MULTISTRING); }
		public ITerminalNode MULTISTRING(int i) {
			return GetToken(STGrammerParser.MULTISTRING, i);
		}
		public ITerminalNode IDENTIFIER() { return GetToken(STGrammerParser.IDENTIFIER, 0); }
		public Disp_defineContext disp_define() {
			return GetRuleContext<Disp_defineContext>(0);
		}
		public Type_defineContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_type_define; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISTGrammerVisitor<TResult> typedVisitor = visitor as ISTGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitType_define(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Type_defineContext type_define() {
		Type_defineContext _localctx = new Type_defineContext(Context, State);
		EnterRule(_localctx, 22, RULE_type_define);
		try {
			State = 192;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,15,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 178; Match(TYPE_INT);
				State = 179; Match(NUM_UINT);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 180; Match(TYPE_UINT);
				State = 181; Match(NUM_UINT);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 182; Match(TYPE_LREAL);
				State = 183; Match(NUM_REAL);
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 184; Match(TYPE_STRING);
				State = 185; Match(MULTISTRING);
				State = 186; Match(IDENTIFIER);
				State = 187; Match(MULTISTRING);
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 188; Match(TYPE_INT);
				State = 189; disp_define();
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 190; Match(TYPE_UINT);
				State = 191; disp_define();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Disp_defineContext : ParserRuleContext {
		public ITerminalNode DISP_BIN() { return GetToken(STGrammerParser.DISP_BIN, 0); }
		public ITerminalNode DISP_OCT() { return GetToken(STGrammerParser.DISP_OCT, 0); }
		public ITerminalNode DISP_HEX() { return GetToken(STGrammerParser.DISP_HEX, 0); }
		public Disp_defineContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_disp_define; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISTGrammerVisitor<TResult> typedVisitor = visitor as ISTGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDisp_define(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Disp_defineContext disp_define() {
		Disp_defineContext _localctx = new Disp_defineContext(Context, State);
		EnterRule(_localctx, 24, RULE_disp_define);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 194;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << DISP_BIN) | (1L << DISP_OCT) | (1L << DISP_HEX))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LinecommentContext : ParserRuleContext {
		public ITerminalNode SINGLE_LINE_COMMENT() { return GetToken(STGrammerParser.SINGLE_LINE_COMMENT, 0); }
		public LinecommentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_linecomment; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISTGrammerVisitor<TResult> typedVisitor = visitor as ISTGrammerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLinecomment(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LinecommentContext linecomment() {
		LinecommentContext _localctx = new LinecommentContext(Context, State);
		EnterRule(_localctx, 26, RULE_linecomment);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 196; Match(SINGLE_LINE_COMMENT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 6: return expr_sempred((ExprContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expr_sempred(ExprContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 15);
		case 1: return Precpred(Context, 14);
		case 2: return Precpred(Context, 13);
		case 3: return Precpred(Context, 12);
		case 4: return Precpred(Context, 11);
		case 5: return Precpred(Context, 10);
		case 6: return Precpred(Context, 9);
		}
		return true;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\x32', '\xC9', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x4', '\xF', '\t', '\xF', '\x3', '\x2', '\a', '\x2', ' ', '\n', 
		'\x2', '\f', '\x2', '\xE', '\x2', '#', '\v', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x5', '\x3', '.', '\n', '\x3', '\x3', 
		'\x4', '\x3', '\x4', '\a', '\x4', '\x32', '\n', '\x4', '\f', '\x4', '\xE', 
		'\x4', '\x35', '\v', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', 
		'\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', 
		'\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x6', '\x6', 
		'\x43', '\n', '\x6', '\r', '\x6', '\xE', '\x6', '\x44', '\x3', '\x6', 
		'\x3', '\x6', '\a', '\x6', 'I', '\n', '\x6', '\f', '\x6', '\xE', '\x6', 
		'L', '\v', '\x6', '\a', '\x6', 'N', '\n', '\x6', '\f', '\x6', '\xE', '\x6', 
		'Q', '\v', '\x6', '\x3', '\x6', '\x3', '\x6', '\a', '\x6', 'U', '\n', 
		'\x6', '\f', '\x6', '\xE', '\x6', 'X', '\v', '\x6', '\x5', '\x6', 'Z', 
		'\n', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x5', '\a', '\x64', '\n', 
		'\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\a', '\b', 'n', '\n', '\b', '\f', 
		'\b', '\xE', '\b', 'q', '\v', '\b', '\x3', '\b', '\x3', '\b', '\a', '\b', 
		'u', '\n', '\b', '\f', '\b', '\xE', '\b', 'x', '\v', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x5', '\b', '\x88', '\n', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\a', '\b', '\x9F', '\n', 
		'\b', '\f', '\b', '\xE', '\b', '\xA2', '\v', '\b', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x5', '\t', '\xAD', '\n', '\t', '\x3', '\n', 
		'\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', 
		'\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', 
		'\r', '\x3', '\r', '\x3', '\r', '\x5', '\r', '\xC3', '\n', '\r', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x2', 
		'\x3', '\xE', '\x10', '\x2', '\x4', '\x6', '\b', '\n', '\f', '\xE', '\x10', 
		'\x12', '\x14', '\x16', '\x18', '\x1A', '\x1C', '\x2', '\v', '\x3', '\x2', 
		'\x3', '\x4', '\x4', '\x2', '\x5', '\a', '\x17', '\x17', '\x3', '\x2', 
		'\x18', '\x1B', '\x3', '\x2', '\b', '\v', '\x3', '\x2', '\f', '\r', '\x3', 
		'\x2', '\xE', '\xF', '\x4', '\x2', '\b', '\r', '\x18', '\x1B', '\x3', 
		'\x2', ')', '*', '\x3', '\x2', '/', '\x31', '\x2', '\xE0', '\x2', '!', 
		'\x3', '\x2', '\x2', '\x2', '\x4', '-', '\x3', '\x2', '\x2', '\x2', '\x6', 
		'/', '\x3', '\x2', '\x2', '\x2', '\b', ';', '\x3', '\x2', '\x2', '\x2', 
		'\n', '>', '\x3', '\x2', '\x2', '\x2', '\f', '\x63', '\x3', '\x2', '\x2', 
		'\x2', '\xE', '\x87', '\x3', '\x2', '\x2', '\x2', '\x10', '\xAC', '\x3', 
		'\x2', '\x2', '\x2', '\x12', '\xAE', '\x3', '\x2', '\x2', '\x2', '\x14', 
		'\xB0', '\x3', '\x2', '\x2', '\x2', '\x16', '\xB2', '\x3', '\x2', '\x2', 
		'\x2', '\x18', '\xC2', '\x3', '\x2', '\x2', '\x2', '\x1A', '\xC4', '\x3', 
		'\x2', '\x2', '\x2', '\x1C', '\xC6', '\x3', '\x2', '\x2', '\x2', '\x1E', 
		' ', '\x5', '\x4', '\x3', '\x2', '\x1F', '\x1E', '\x3', '\x2', '\x2', 
		'\x2', ' ', '#', '\x3', '\x2', '\x2', '\x2', '!', '\x1F', '\x3', '\x2', 
		'\x2', '\x2', '!', '\"', '\x3', '\x2', '\x2', '\x2', '\"', '$', '\x3', 
		'\x2', '\x2', '\x2', '#', '!', '\x3', '\x2', '\x2', '\x2', '$', '%', '\a', 
		'\x2', '\x2', '\x3', '%', '\x3', '\x3', '\x2', '\x2', '\x2', '&', '.', 
		'\x5', '\x6', '\x4', '\x2', '\'', '.', '\x5', '\b', '\x5', '\x2', '(', 
		'.', '\x5', '\n', '\x6', '\x2', ')', '*', '\x5', '\xE', '\b', '\x2', '*', 
		'+', '\a', '\x14', '\x2', '\x2', '+', '.', '\x3', '\x2', '\x2', '\x2', 
		',', '.', '\x5', '\x1C', '\xF', '\x2', '-', '&', '\x3', '\x2', '\x2', 
		'\x2', '-', '\'', '\x3', '\x2', '\x2', '\x2', '-', '(', '\x3', '\x2', 
		'\x2', '\x2', '-', ')', '\x3', '\x2', '\x2', '\x2', '-', ',', '\x3', '\x2', 
		'\x2', '\x2', '.', '\x5', '\x3', '\x2', '\x2', '\x2', '/', '\x33', '\a', 
		'\x1F', '\x2', '\x2', '\x30', '\x32', '\x5', '\x4', '\x3', '\x2', '\x31', 
		'\x30', '\x3', '\x2', '\x2', '\x2', '\x32', '\x35', '\x3', '\x2', '\x2', 
		'\x2', '\x33', '\x31', '\x3', '\x2', '\x2', '\x2', '\x33', '\x34', '\x3', 
		'\x2', '\x2', '\x2', '\x34', '\x36', '\x3', '\x2', '\x2', '\x2', '\x35', 
		'\x33', '\x3', '\x2', '\x2', '\x2', '\x36', '\x37', '\a', ' ', '\x2', 
		'\x2', '\x37', '\x38', '\x5', '\xE', '\b', '\x2', '\x38', '\x39', '\a', 
		'#', '\x2', '\x2', '\x39', ':', '\a', '\x14', '\x2', '\x2', ':', '\a', 
		'\x3', '\x2', '\x2', '\x2', ';', '<', '\a', '\"', '\x2', '\x2', '<', '=', 
		'\a', '\x14', '\x2', '\x2', '=', '\t', '\x3', '\x2', '\x2', '\x2', '>', 
		'?', '\a', '\x1C', '\x2', '\x2', '?', '@', '\x5', '\xE', '\b', '\x2', 
		'@', 'O', '\a', '\x1D', '\x2', '\x2', '\x41', '\x43', '\x5', '\f', '\a', 
		'\x2', '\x42', '\x41', '\x3', '\x2', '\x2', '\x2', '\x43', '\x44', '\x3', 
		'\x2', '\x2', '\x2', '\x44', '\x42', '\x3', '\x2', '\x2', '\x2', '\x44', 
		'\x45', '\x3', '\x2', '\x2', '\x2', '\x45', '\x46', '\x3', '\x2', '\x2', 
		'\x2', '\x46', 'J', '\a', '\x15', '\x2', '\x2', 'G', 'I', '\x5', '\x4', 
		'\x3', '\x2', 'H', 'G', '\x3', '\x2', '\x2', '\x2', 'I', 'L', '\x3', '\x2', 
		'\x2', '\x2', 'J', 'H', '\x3', '\x2', '\x2', '\x2', 'J', 'K', '\x3', '\x2', 
		'\x2', '\x2', 'K', 'N', '\x3', '\x2', '\x2', '\x2', 'L', 'J', '\x3', '\x2', 
		'\x2', '\x2', 'M', '\x42', '\x3', '\x2', '\x2', '\x2', 'N', 'Q', '\x3', 
		'\x2', '\x2', '\x2', 'O', 'M', '\x3', '\x2', '\x2', '\x2', 'O', 'P', '\x3', 
		'\x2', '\x2', '\x2', 'P', 'Y', '\x3', '\x2', '\x2', '\x2', 'Q', 'O', '\x3', 
		'\x2', '\x2', '\x2', 'R', 'V', '\a', '!', '\x2', '\x2', 'S', 'U', '\x5', 
		'\x4', '\x3', '\x2', 'T', 'S', '\x3', '\x2', '\x2', '\x2', 'U', 'X', '\x3', 
		'\x2', '\x2', '\x2', 'V', 'T', '\x3', '\x2', '\x2', '\x2', 'V', 'W', '\x3', 
		'\x2', '\x2', '\x2', 'W', 'Z', '\x3', '\x2', '\x2', '\x2', 'X', 'V', '\x3', 
		'\x2', '\x2', '\x2', 'Y', 'R', '\x3', '\x2', '\x2', '\x2', 'Y', 'Z', '\x3', 
		'\x2', '\x2', '\x2', 'Z', '[', '\x3', '\x2', '\x2', '\x2', '[', '\\', 
		'\a', '\x1E', '\x2', '\x2', '\\', ']', '\a', '\x14', '\x2', '\x2', ']', 
		'\v', '\x3', '\x2', '\x2', '\x2', '^', '\x64', '\a', '\x32', '\x2', '\x2', 
		'_', '`', '\a', '\x11', '\x2', '\x2', '`', '\x64', '\a', '\x32', '\x2', 
		'\x2', '\x61', '\x62', '\a', '\x10', '\x2', '\x2', '\x62', '\x64', '\a', 
		'\x32', '\x2', '\x2', '\x63', '^', '\x3', '\x2', '\x2', '\x2', '\x63', 
		'_', '\x3', '\x2', '\x2', '\x2', '\x63', '\x61', '\x3', '\x2', '\x2', 
		'\x2', '\x64', '\r', '\x3', '\x2', '\x2', '\x2', '\x65', '\x66', '\b', 
		'\b', '\x1', '\x2', '\x66', 'g', '\t', '\x2', '\x2', '\x2', 'g', '\x88', 
		'\x5', '\xE', '\b', '\x13', 'h', 'i', '\a', '\x16', '\x2', '\x2', 'i', 
		'\x88', '\x5', '\x10', '\t', '\x2', 'j', 'k', '\a', '\x32', '\x2', '\x2', 
		'k', 'o', '\a', '\x12', '\x2', '\x2', 'l', 'n', '\x5', '\x10', '\t', '\x2', 
		'm', 'l', '\x3', '\x2', '\x2', '\x2', 'n', 'q', '\x3', '\x2', '\x2', '\x2', 
		'o', 'm', '\x3', '\x2', '\x2', '\x2', 'o', 'p', '\x3', '\x2', '\x2', '\x2', 
		'p', 'v', '\x3', '\x2', '\x2', '\x2', 'q', 'o', '\x3', '\x2', '\x2', '\x2', 
		'r', 's', '\a', '\x11', '\x2', '\x2', 's', 'u', '\x5', '\x10', '\t', '\x2', 
		't', 'r', '\x3', '\x2', '\x2', '\x2', 'u', 'x', '\x3', '\x2', '\x2', '\x2', 
		'v', 't', '\x3', '\x2', '\x2', '\x2', 'v', 'w', '\x3', '\x2', '\x2', '\x2', 
		'w', 'y', '\x3', '\x2', '\x2', '\x2', 'x', 'v', '\x3', '\x2', '\x2', '\x2', 
		'y', '\x88', '\a', '\x13', '\x2', '\x2', 'z', '{', '\a', '%', '\x2', '\x2', 
		'{', '|', '\x5', '\xE', '\b', '\x2', '|', '}', '\a', '%', '\x2', '\x2', 
		'}', '\x88', '\x3', '\x2', '\x2', '\x2', '~', '\x7F', '\a', '&', '\x2', 
		'\x2', '\x7F', '\x80', '\x5', '\xE', '\b', '\x2', '\x80', '\x81', '\a', 
		'&', '\x2', '\x2', '\x81', '\x88', '\x3', '\x2', '\x2', '\x2', '\x82', 
		'\x88', '\x5', '\x14', '\v', '\x2', '\x83', '\x88', '\x5', '\x18', '\r', 
		'\x2', '\x84', '\x88', '\x5', '\x1A', '\xE', '\x2', '\x85', '\x88', '\x5', 
		'\x16', '\f', '\x2', '\x86', '\x88', '\x5', '\x12', '\n', '\x2', '\x87', 
		'\x65', '\x3', '\x2', '\x2', '\x2', '\x87', 'h', '\x3', '\x2', '\x2', 
		'\x2', '\x87', 'j', '\x3', '\x2', '\x2', '\x2', '\x87', 'z', '\x3', '\x2', 
		'\x2', '\x2', '\x87', '~', '\x3', '\x2', '\x2', '\x2', '\x87', '\x82', 
		'\x3', '\x2', '\x2', '\x2', '\x87', '\x83', '\x3', '\x2', '\x2', '\x2', 
		'\x87', '\x84', '\x3', '\x2', '\x2', '\x2', '\x87', '\x85', '\x3', '\x2', 
		'\x2', '\x2', '\x87', '\x86', '\x3', '\x2', '\x2', '\x2', '\x88', '\xA0', 
		'\x3', '\x2', '\x2', '\x2', '\x89', '\x8A', '\f', '\x11', '\x2', '\x2', 
		'\x8A', '\x8B', '\t', '\x2', '\x2', '\x2', '\x8B', '\x9F', '\x5', '\xE', 
		'\b', '\x12', '\x8C', '\x8D', '\f', '\x10', '\x2', '\x2', '\x8D', '\x8E', 
		'\t', '\x3', '\x2', '\x2', '\x8E', '\x9F', '\x5', '\xE', '\b', '\x11', 
		'\x8F', '\x90', '\f', '\xF', '\x2', '\x2', '\x90', '\x91', '\t', '\x4', 
		'\x2', '\x2', '\x91', '\x9F', '\x5', '\xE', '\b', '\x10', '\x92', '\x93', 
		'\f', '\xE', '\x2', '\x2', '\x93', '\x94', '\t', '\x5', '\x2', '\x2', 
		'\x94', '\x9F', '\x5', '\xE', '\b', '\xF', '\x95', '\x96', '\f', '\r', 
		'\x2', '\x2', '\x96', '\x97', '\t', '\x6', '\x2', '\x2', '\x97', '\x9F', 
		'\x5', '\xE', '\b', '\xE', '\x98', '\x99', '\f', '\f', '\x2', '\x2', '\x99', 
		'\x9A', '\a', '\xE', '\x2', '\x2', '\x9A', '\x9F', '\x5', '\xE', '\b', 
		'\r', '\x9B', '\x9C', '\f', '\v', '\x2', '\x2', '\x9C', '\x9D', '\a', 
		'\xF', '\x2', '\x2', '\x9D', '\x9F', '\x5', '\xE', '\b', '\f', '\x9E', 
		'\x89', '\x3', '\x2', '\x2', '\x2', '\x9E', '\x8C', '\x3', '\x2', '\x2', 
		'\x2', '\x9E', '\x8F', '\x3', '\x2', '\x2', '\x2', '\x9E', '\x92', '\x3', 
		'\x2', '\x2', '\x2', '\x9E', '\x95', '\x3', '\x2', '\x2', '\x2', '\x9E', 
		'\x98', '\x3', '\x2', '\x2', '\x2', '\x9E', '\x9B', '\x3', '\x2', '\x2', 
		'\x2', '\x9F', '\xA2', '\x3', '\x2', '\x2', '\x2', '\xA0', '\x9E', '\x3', 
		'\x2', '\x2', '\x2', '\xA0', '\xA1', '\x3', '\x2', '\x2', '\x2', '\xA1', 
		'\xF', '\x3', '\x2', '\x2', '\x2', '\xA2', '\xA0', '\x3', '\x2', '\x2', 
		'\x2', '\xA3', '\xA4', '\x5', '\xE', '\b', '\x2', '\xA4', '\xA5', '\t', 
		'\a', '\x2', '\x2', '\xA5', '\xA6', '\x5', '\xE', '\b', '\x2', '\xA6', 
		'\xAD', '\x3', '\x2', '\x2', '\x2', '\xA7', '\xA8', '\x5', '\xE', '\b', 
		'\x2', '\xA8', '\xA9', '\t', '\b', '\x2', '\x2', '\xA9', '\xAA', '\x5', 
		'\xE', '\b', '\x2', '\xAA', '\xAD', '\x3', '\x2', '\x2', '\x2', '\xAB', 
		'\xAD', '\x5', '\x12', '\n', '\x2', '\xAC', '\xA3', '\x3', '\x2', '\x2', 
		'\x2', '\xAC', '\xA7', '\x3', '\x2', '\x2', '\x2', '\xAC', '\xAB', '\x3', 
		'\x2', '\x2', '\x2', '\xAD', '\x11', '\x3', '\x2', '\x2', '\x2', '\xAE', 
		'\xAF', '\a', '\x32', '\x2', '\x2', '\xAF', '\x13', '\x3', '\x2', '\x2', 
		'\x2', '\xB0', '\xB1', '\a', '$', '\x2', '\x2', '\xB1', '\x15', '\x3', 
		'\x2', '\x2', '\x2', '\xB2', '\xB3', '\t', '\t', '\x2', '\x2', '\xB3', 
		'\x17', '\x3', '\x2', '\x2', '\x2', '\xB4', '\xB5', '\a', '+', '\x2', 
		'\x2', '\xB5', '\xC3', '\a', ')', '\x2', '\x2', '\xB6', '\xB7', '\a', 
		',', '\x2', '\x2', '\xB7', '\xC3', '\a', ')', '\x2', '\x2', '\xB8', '\xB9', 
		'\a', '-', '\x2', '\x2', '\xB9', '\xC3', '\a', '*', '\x2', '\x2', '\xBA', 
		'\xBB', '\a', '.', '\x2', '\x2', '\xBB', '\xBC', '\a', '%', '\x2', '\x2', 
		'\xBC', '\xBD', '\a', '\x32', '\x2', '\x2', '\xBD', '\xC3', '\a', '%', 
		'\x2', '\x2', '\xBE', '\xBF', '\a', '+', '\x2', '\x2', '\xBF', '\xC3', 
		'\x5', '\x1A', '\xE', '\x2', '\xC0', '\xC1', '\a', ',', '\x2', '\x2', 
		'\xC1', '\xC3', '\x5', '\x1A', '\xE', '\x2', '\xC2', '\xB4', '\x3', '\x2', 
		'\x2', '\x2', '\xC2', '\xB6', '\x3', '\x2', '\x2', '\x2', '\xC2', '\xB8', 
		'\x3', '\x2', '\x2', '\x2', '\xC2', '\xBA', '\x3', '\x2', '\x2', '\x2', 
		'\xC2', '\xBE', '\x3', '\x2', '\x2', '\x2', '\xC2', '\xC0', '\x3', '\x2', 
		'\x2', '\x2', '\xC3', '\x19', '\x3', '\x2', '\x2', '\x2', '\xC4', '\xC5', 
		'\t', '\n', '\x2', '\x2', '\xC5', '\x1B', '\x3', '\x2', '\x2', '\x2', 
		'\xC6', '\xC7', '\a', '(', '\x2', '\x2', '\xC7', '\x1D', '\x3', '\x2', 
		'\x2', '\x2', '\x12', '!', '-', '\x33', '\x44', 'J', 'O', 'V', 'Y', '\x63', 
		'o', 'v', '\x87', '\x9E', '\xA0', '\xAC', '\xC2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
