//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/takuumi/Projects/StudyANTLR/Part3/STtoKVScript/KVScriptGrammer.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="KVScriptGrammerParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface IKVScriptGrammerVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="KVScriptGrammerParser.input"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInput([NotNull] KVScriptGrammerParser.InputContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KVScriptGrammerParser.oneline"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOneline([NotNull] KVScriptGrammerParser.OnelineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KVScriptGrammerParser.kvlang"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKvlang([NotNull] KVScriptGrammerParser.KvlangContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expr_define</c>
	/// labeled alternative in <see cref="KVScriptGrammerParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr_define([NotNull] KVScriptGrammerParser.Expr_defineContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expr_additive</c>
	/// labeled alternative in <see cref="KVScriptGrammerParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr_additive([NotNull] KVScriptGrammerParser.Expr_additiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KVScriptGrammerParser.define"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefine([NotNull] KVScriptGrammerParser.DefineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KVScriptGrammerParser.linecomment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLinecomment([NotNull] KVScriptGrammerParser.LinecommentContext context);
}
